### ISSUE TITLE
#61 [FIX] CI에서 제대로 업뎃 못하는 문제를 해결해요.

### ISSUE THREAD

**Issue by GeunSam2** [beezSSG/finalproject_pickme_back#152]
CI 파일 이렇게 업뎃 해주세용

```
name: Build and Push Docker Image and Modify EKS Repo #

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: pickme_back
      ECR_REGISTRY: 709745608741.dkr.ecr.ap-northeast-2.amazonaws.com
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Create properties files
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties
          echo "${{ secrets.DB_PROPERTIES }}" > src/main/resources/db.properties
          echo "${{ secrets.KEY_PROPERTIES }}" > src/main/resources/key.properties
          echo "${{ secrets.MAIL_PROPERTIES }}" > src/main/resources/mail.properties
      
      #- name: Print properties content
        #run: cat src/main/resources/db.properties

      #- name: Login to Amazon ECR Public
        #run: |
          #aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      #- name: Create .env file
        #run: |
         # echo "${{ secrets.ENV_VARS }}" > .env

      - name: Build and push Docker image to Amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

  modify-eks-repo:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: pickme_back
      ECR_REGISTRY: 709745608741.dkr.ecr.ap-northeast-2.amazonaws.com
      EKS_PATH: projects/prickme-back
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: beezSSG/Devops
          token: ${{ secrets.REPO_TOKEN }} 
          path: Devops

      - name: Modify Files and Commit
        run: |
          cd Devops
          mkdir -p ${{ env.EKS_PATH}}
          touch ${{ env.EKS_PATH }}/values.yaml
          sed -i "s#image:.*#image: \"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"#g" ${{ env.EKS_PATH }}/values.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update front by GitHub Actions"

      - name: Push Changes
        run: |
          cd Devops
          git pull --rebase
          git push
```
